### ISSUE TITLE
no sound and no microphone

### ISSUE THREAD

**Issue by rlsl** [droidian-vayu/droidian-images#1] opened 2023-07-28 13:14 UTC
I installed the droidian image, latest release, and it finished successfully, for fastboot, the droidian is working ok except the sound and the microphone, however when I put a bluetooth speaker and receive a call there is a sound warning in it and the microphone worked when wearing headphones with a microphone.

**Comment by vacuumbeef** [comment] 2023-10-24 07:34
Hello, I'm sorry for VERY late reply, I had a very long rest from Droidian stuff.
I found out that flash_all.bat file does not include vendor.img flashing line, while .sh file is alright. If you was flashing from windows, this is what caused it probably.
I'll close the issue.

**Closed as completed by vacuumbeef** 2023-10-24 07:34 UTC

**Comment by linuxuser2064** [comment] 2024-11-09 08:07
Is that fixed in the script now or not, I also had that exact issue.
If not, then that should be in the docs.

**Comment by vacuumbeef** [comment] 2024-11-09 08:55
Yes, it was fixed when I found it out. You can look in the script - if it has `fastboot flash vendor data/vendor.img` line - then everything is good.

Usually this kind of issues are happening if you haven't flashed the right firmware - https://xmfirmwareupdater.com/miui/vayu/stable/V12.5.9.0.RJUMIXM/ or you flashed through regular fastboot, instead of fastbootD

At least the latest release was tested many times by many people, and we all have the same phones, so there is not much I can say. I can try to flash from windows tomorrow evening to be 100% sure

**Comment by vacuumbeef** [comment] 2024-11-10 14:49
Yes I confirm it works. Just flashed latest nightly from windows using `flash_all.bat`, sound works.
The problem is either wrong firmware or fastboot instead of fastbootd (it can't flash vendor in regular fastboot).
